const weatherObj = {
  location: {
    name: "Pune",
    region: "Maharashtra",
    country: "India",
    lat: 18.5333,
    lon: 73.8667,
    tz_id: "Asia/Kolkata",
    localtime_epoch: 1733848514,
    localtime: "2024-12-10 22:05",
  },
  current: {
    last_updated_epoch: 1733848200,
    last_updated: "2024-12-10 22:00",
    temp_c: 19.1,
    temp_f: 66.4,
    is_day: 0,
    condition: {
      text: "Clear",
      icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
      code: 1000,
    },
    wind_mph: 5.1,
    wind_kph: 8.3,
    wind_degree: 88,
    wind_dir: "E",
    pressure_mb: 1015,
    pressure_in: 29.97,
    precip_mm: 0,
    precip_in: 0,
    humidity: 41,
    cloud: 4,
    feelslike_c: 19.1,
    feelslike_f: 66.5,
    windchill_c: 19.1,
    windchill_f: 66.5,
    heatindex_c: 19.1,
    heatindex_f: 66.5,
    dewpoint_c: 5.8,
    dewpoint_f: 42.4,
    vis_km: 10,
    vis_miles: 6,
    uv: 0,
    gust_mph: 10.8,
    gust_kph: 17.4,
    air_quality: {
      co: 606.8,
      no2: 18.5,
      o3: 130,
      so2: 15.54,
      pm2_5: 45.325,
      pm10: 46.065,
      "us-epa-index": 3,
      "gb-defra-index": 5,
    },
  },
  forecast: {
    forecastday: [
      {
        date: "2024-12-10",
        date_epoch: 1733788800,
        day: {
          maxtemp_c: 28.1,
          maxtemp_f: 82.5,
          mintemp_c: 15.3,
          mintemp_f: 59.6,
          avgtemp_c: 21.1,
          avgtemp_f: 70,
          maxwind_mph: 8.9,
          maxwind_kph: 14.4,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 34,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 1.5,
        },
        astro: {
          sunrise: "06:56 AM",
          sunset: "05:59 PM",
          moonrise: "01:50 PM",
          moonset: "01:34 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: 65,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1733769000,
            time: "2024-12-10 00:00",
            temp_c: 17.9,
            temp_f: 64.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 55,
            wind_dir: "NE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 5,
            feelslike_c: 17.9,
            feelslike_f: 64.3,
            windchill_c: 17.9,
            windchill_f: 64.3,
            heatindex_c: 17.9,
            heatindex_f: 64.3,
            dewpoint_c: 3.9,
            dewpoint_f: 39.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
          {
            time_epoch: 1733772600,
            time: "2024-12-10 01:00",
            temp_c: 17.3,
            temp_f: 63.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 43,
            wind_dir: "NE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 37,
            cloud: 7,
            feelslike_c: 17.3,
            feelslike_f: 63.2,
            windchill_c: 17.3,
            windchill_f: 63.2,
            heatindex_c: 17.3,
            heatindex_f: 63.2,
            dewpoint_c: 2.6,
            dewpoint_f: 36.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 0,
          },
          {
            time_epoch: 1733776200,
            time: "2024-12-10 02:00",
            temp_c: 16.8,
            temp_f: 62.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 52,
            wind_dir: "NE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 9,
            feelslike_c: 16.8,
            feelslike_f: 62.3,
            windchill_c: 16.8,
            windchill_f: 62.3,
            heatindex_c: 16.8,
            heatindex_f: 62.3,
            dewpoint_c: 1.7,
            dewpoint_f: 35.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
          {
            time_epoch: 1733779800,
            time: "2024-12-10 03:00",
            temp_c: 16.3,
            temp_f: 61.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 56,
            wind_dir: "ENE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 9,
            feelslike_c: 16.3,
            feelslike_f: 61.4,
            windchill_c: 16.3,
            windchill_f: 61.4,
            heatindex_c: 16.3,
            heatindex_f: 61.4,
            dewpoint_c: 1.4,
            dewpoint_f: 34.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 0,
          },
          {
            time_epoch: 1733783400,
            time: "2024-12-10 04:00",
            temp_c: 16,
            temp_f: 60.9,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 9,
            feelslike_c: 16.1,
            feelslike_f: 60.9,
            windchill_c: 16.1,
            windchill_f: 60.9,
            heatindex_c: 16.1,
            heatindex_f: 60.9,
            dewpoint_c: 1.1,
            dewpoint_f: 34,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
          {
            time_epoch: 1733787000,
            time: "2024-12-10 05:00",
            temp_c: 15.6,
            temp_f: 60.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 75,
            wind_dir: "ENE",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 8,
            feelslike_c: 15.6,
            feelslike_f: 60.1,
            windchill_c: 15.6,
            windchill_f: 60.1,
            heatindex_c: 15.6,
            heatindex_f: 60.1,
            dewpoint_c: 0.7,
            dewpoint_f: 33.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 0,
          },
          {
            time_epoch: 1733790600,
            time: "2024-12-10 06:00",
            temp_c: 15.3,
            temp_f: 59.6,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 87,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 8,
            feelslike_c: 15.3,
            feelslike_f: 59.6,
            windchill_c: 15.3,
            windchill_f: 59.6,
            heatindex_c: 15.3,
            heatindex_f: 59.6,
            dewpoint_c: 0.3,
            dewpoint_f: 32.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
          {
            time_epoch: 1733794200,
            time: "2024-12-10 07:00",
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 87,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 8,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            windchill_c: 16.5,
            windchill_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: 1.6,
            dewpoint_f: 34.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
          {
            time_epoch: 1733797800,
            time: "2024-12-10 08:00",
            temp_c: 19.1,
            temp_f: 66.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 78,
            wind_dir: "ENE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 30,
            cloud: 9,
            feelslike_c: 19.1,
            feelslike_f: 66.3,
            windchill_c: 19.1,
            windchill_f: 66.3,
            heatindex_c: 19.1,
            heatindex_f: 66.3,
            dewpoint_c: 1.2,
            dewpoint_f: 34.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.8,
            gust_kph: 11,
            uv: 0.8,
          },
          {
            time_epoch: 1733801400,
            time: "2024-12-10 09:00",
            temp_c: 21.3,
            temp_f: 70.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 84,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 26,
            cloud: 9,
            feelslike_c: 21.3,
            feelslike_f: 70.4,
            windchill_c: 21.3,
            windchill_f: 70.4,
            heatindex_c: 22.6,
            heatindex_f: 72.7,
            dewpoint_c: 1.2,
            dewpoint_f: 34.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.2,
            gust_kph: 13.2,
            uv: 2.3,
          },
          {
            time_epoch: 1733805000,
            time: "2024-12-10 10:00",
            temp_c: 23.4,
            temp_f: 74.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 87,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 25,
            cloud: 8,
            feelslike_c: 23.4,
            feelslike_f: 74,
            windchill_c: 23.4,
            windchill_f: 74.1,
            heatindex_c: 23.4,
            heatindex_f: 74,
            dewpoint_c: 2.3,
            dewpoint_f: 36.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 4.4,
          },
          {
            time_epoch: 1733808600,
            time: "2024-12-10 11:00",
            temp_c: 25,
            temp_f: 77,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 84,
            wind_dir: "E",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 25,
            cloud: 6,
            feelslike_c: 24.3,
            feelslike_f: 75.8,
            windchill_c: 25,
            windchill_f: 77,
            heatindex_c: 24.3,
            heatindex_f: 75.8,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 6.2,
          },
          {
            time_epoch: 1733812200,
            time: "2024-12-10 12:00",
            temp_c: 26.4,
            temp_f: 79.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 98,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 26,
            cloud: 6,
            feelslike_c: 25.3,
            feelslike_f: 77.6,
            windchill_c: 26.4,
            windchill_f: 79.6,
            heatindex_c: 25.3,
            heatindex_f: 77.6,
            dewpoint_c: 5.3,
            dewpoint_f: 41.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 7.1,
          },
          {
            time_epoch: 1733815800,
            time: "2024-12-10 13:00",
            temp_c: 27.4,
            temp_f: 81.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 26,
            cloud: 6,
            feelslike_c: 26.1,
            feelslike_f: 79,
            windchill_c: 27.4,
            windchill_f: 81.2,
            heatindex_c: 26.1,
            heatindex_f: 79,
            dewpoint_c: 6.4,
            dewpoint_f: 43.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.5,
            gust_kph: 15.3,
            uv: 6.5,
          },
          {
            time_epoch: 1733819400,
            time: "2024-12-10 14:00",
            temp_c: 27.9,
            temp_f: 82.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 103,
            wind_dir: "ESE",
            pressure_mb: 1011,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 27,
            cloud: 5,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 27.9,
            windchill_f: 82.3,
            heatindex_c: 26.6,
            heatindex_f: 79.9,
            dewpoint_c: 7.2,
            dewpoint_f: 44.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 4.8,
          },
          {
            time_epoch: 1733823000,
            time: "2024-12-10 15:00",
            temp_c: 28.1,
            temp_f: 82.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 104,
            wind_dir: "ESE",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 28,
            cloud: 4,
            feelslike_c: 26.8,
            feelslike_f: 80.2,
            windchill_c: 28.1,
            windchill_f: 82.5,
            heatindex_c: 26.8,
            heatindex_f: 80.2,
            dewpoint_c: 7.7,
            dewpoint_f: 45.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12,
            uv: 2.6,
          },
          {
            time_epoch: 1733826600,
            time: "2024-12-10 16:00",
            temp_c: 27.8,
            temp_f: 82,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 101,
            wind_dir: "ESE",
            pressure_mb: 1010,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 29,
            cloud: 4,
            feelslike_c: 26.7,
            feelslike_f: 80,
            windchill_c: 27.8,
            windchill_f: 82,
            heatindex_c: 26.7,
            heatindex_f: 80,
            dewpoint_c: 8.1,
            dewpoint_f: 46.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.2,
            gust_kph: 9.9,
            uv: 1,
          },
          {
            time_epoch: 1733830200,
            time: "2024-12-10 17:00",
            temp_c: 25.3,
            temp_f: 77.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 86,
            wind_dir: "E",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 36,
            cloud: 4,
            feelslike_c: 25.3,
            feelslike_f: 77.5,
            windchill_c: 25.3,
            windchill_f: 77.5,
            heatindex_c: 25.3,
            heatindex_f: 77.5,
            dewpoint_c: 9,
            dewpoint_f: 48.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.6,
            gust_kph: 13.8,
            uv: 0.2,
          },
          {
            time_epoch: 1733833800,
            time: "2024-12-10 18:00",
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 79,
            wind_dir: "E",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 38,
            cloud: 4,
            feelslike_c: 24,
            feelslike_f: 75.3,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24,
            heatindex_f: 75.3,
            dewpoint_c: 7.5,
            dewpoint_f: 45.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.6,
            uv: 0,
          },
          {
            time_epoch: 1733837400,
            time: "2024-12-10 19:00",
            temp_c: 21.8,
            temp_f: 71.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 39,
            cloud: 4,
            feelslike_c: 21.8,
            feelslike_f: 71.2,
            windchill_c: 21.8,
            windchill_f: 71.2,
            heatindex_c: 23.9,
            heatindex_f: 75.1,
            dewpoint_c: 7.3,
            dewpoint_f: 45.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.9,
            gust_kph: 15.9,
            uv: 0,
          },
          {
            time_epoch: 1733841000,
            time: "2024-12-10 20:00",
            temp_c: 21.2,
            temp_f: 70.1,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 77,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 40,
            cloud: 4,
            feelslike_c: 21.2,
            feelslike_f: 70.1,
            windchill_c: 21.2,
            windchill_f: 70.1,
            heatindex_c: 23.9,
            heatindex_f: 74.9,
            dewpoint_c: 7.1,
            dewpoint_f: 44.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.9,
            gust_kph: 15.9,
            uv: 0,
          },
          {
            time_epoch: 1733844600,
            time: "2024-12-10 21:00",
            temp_c: 20.1,
            temp_f: 68.2,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 68,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 4,
            feelslike_c: 20.1,
            feelslike_f: 68.2,
            windchill_c: 20.1,
            windchill_f: 68.2,
            heatindex_c: 20.1,
            heatindex_f: 68.2,
            dewpoint_c: 6.5,
            dewpoint_f: 43.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 0,
          },
          {
            time_epoch: 1733848200,
            time: "2024-12-10 22:00",
            temp_c: 19.1,
            temp_f: 66.4,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 41,
            cloud: 4,
            feelslike_c: 19.1,
            feelslike_f: 66.5,
            windchill_c: 19.1,
            windchill_f: 66.5,
            heatindex_c: 19.1,
            heatindex_f: 66.5,
            dewpoint_c: 5.8,
            dewpoint_f: 42.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.8,
            gust_kph: 17.4,
            uv: 0,
          },
          {
            time_epoch: 1733851800,
            time: "2024-12-10 23:00",
            temp_c: 18.5,
            temp_f: 65.3,
            is_day: 0,
            condition: {
              text: "Clear ",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 103,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 42,
            cloud: 5,
            feelslike_c: 18.5,
            feelslike_f: 65.3,
            windchill_c: 18.5,
            windchill_f: 65.3,
            heatindex_c: 18.5,
            heatindex_f: 65.3,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
        ],
      },
    ],
  },
};

export default weatherObj;
